name = "newsletter-pages"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "NEWSLETTER_DB"
database_name = "newsletter_subscribers"
database_id = "..."

[env.production.vars]
NEWSLETTER_SITE_URL = "https://aktagon.com"
NEWSLETTER_FROM_EMAIL = "newsletter@aktagon.com"

[env.production.secrets]
# Set with: wrangler secret put RESEND_API_KEY