name = "newsletter"
main = "index.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./assets"
binding = "ASSETS"

[[d1_databases]]
binding = "NEWSLETTER_DB"
database_name = "newsletter_subscribers"
# See README.md for details on how to create database and retrieve ID
database_id = "..."


[triggers]
crons = ["0 9 * * MON"]

[env.production.vars]
NEWSLETTER_SITE_URL = "https://aktagon.com"
NEWSLETTER_FROM_EMAIL = "newsletter@aktagon.com"

[env.production.secrets]
# Set with: wrangler secret put RESEND_API_KEY
# Set with: wrangler secret put NEWSLETTER_WEEKLY_COMMENTARY
